
package gr.scriptum.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProtocolWebServiceService", targetNamespace = "http://wserver.eprotocol.scriptum.gr/", wsdlLocation = "http://10.1.6.86:8080/eProtocolWebService/ProtocolWebService?wsdl")
public class ProtocolWebServiceService
    extends Service
{

    private final static URL PROTOCOLWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gr.scriptum.webservice.client.ProtocolWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gr.scriptum.webservice.client.ProtocolWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://10.1.6.86:8080/eProtocolWebService/ProtocolWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.1.6.86:8080/eProtocolWebService/ProtocolWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROTOCOLWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ProtocolWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProtocolWebServiceService() {
        super(PROTOCOLWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://wserver.eprotocol.scriptum.gr/", "ProtocolWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns EProtocolWebService
     */
    @WebEndpoint(name = "ProtocolWebServicePort")
    public EProtocolWebService getProtocolWebServicePort() {
        return super.getPort(new QName("http://wserver.eprotocol.scriptum.gr/", "ProtocolWebServicePort"), EProtocolWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EProtocolWebService
     */
    @WebEndpoint(name = "ProtocolWebServicePort")
    public EProtocolWebService getProtocolWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wserver.eprotocol.scriptum.gr/", "ProtocolWebServicePort"), EProtocolWebService.class, features);
    }

}
