
package gr.scriptum.webservice.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "faultInfo", targetNamespace = "http://wserver.eprotocol.scriptum.gr/")
public class ProtocolWebServiceFault
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProtocolWebServiceFaultBean faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProtocolWebServiceFault(String message, ProtocolWebServiceFaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProtocolWebServiceFault(String message, ProtocolWebServiceFaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: gr.scriptum.webservice.client.ProtocolWebServiceFaultBean
     */
    public ProtocolWebServiceFaultBean getFaultInfo() {
        return faultInfo;
    }

}
