package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * ApplicationLog generated by hbm2java
 */
public class ApplicationLog implements java.io.Serializable {

	private Integer id;
	private String appuser;
	private String system;
	private String class_;
	private String level;
	private String message;
	private String msgData;
	private Date created;

	public ApplicationLog() {
	}

	public ApplicationLog(String appuser, String system, String class_,
			String level, String message, String msgData, Date created) {
		this.appuser = appuser;
		this.system = system;
		this.class_ = class_;
		this.level = level;
		this.message = message;
		this.msgData = msgData;
		this.created = created;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAppuser() {
		return this.appuser;
	}

	public void setAppuser(String appuser) {
		this.appuser = appuser;
	}

	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getMsgData() {
		return this.msgData;
	}

	public void setMsgData(String msgData) {
		this.msgData = msgData;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
