package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * ApplicationParameter generated by hbm2java
 */
public class ApplicationParameter implements java.io.Serializable {

	private Integer id;
	private String domain;
	private Integer applicationParameterType;
	private String parameterValue;
	private String defaultValue;
	private Integer lastValue;
	private String createUser;
	private String updateUser;
	private Date createDt;
	private Date updateTs;

	public ApplicationParameter() {
	}

	public ApplicationParameter(String domain,
			Integer applicationParameterType, String parameterValue,
			String defaultValue, Integer lastValue, String createUser,
			String updateUser, Date createDt, Date updateTs) {
		this.domain = domain;
		this.applicationParameterType = applicationParameterType;
		this.parameterValue = parameterValue;
		this.defaultValue = defaultValue;
		this.lastValue = lastValue;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public Integer getApplicationParameterType() {
		return this.applicationParameterType;
	}

	public void setApplicationParameterType(Integer applicationParameterType) {
		this.applicationParameterType = applicationParameterType;
	}

	public String getParameterValue() {
		return this.parameterValue;
	}

	public void setParameterValue(String parameterValue) {
		this.parameterValue = parameterValue;
	}

	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public Integer getLastValue() {
		return this.lastValue;
	}

	public void setLastValue(Integer lastValue) {
		this.lastValue = lastValue;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

}
