package gr.scriptum.domain;

// Generated Jan 29, 2011 10:16:29 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CompanyType generated by hbm2java
 */
public class CompanyType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Date createDt;
	private Date updateTs;
	private String crateUser;
	private String updateUser;
	private Set<Company> companies = new HashSet<Company>(0);

	public CompanyType() {
	}

	public CompanyType(String name, String description, Date createDt,
			Date updateTs, String crateUser, String updateUser,
			Set<Company> companies) {
		this.name = name;
		this.description = description;
		this.createDt = createDt;
		this.updateTs = updateTs;
		this.crateUser = crateUser;
		this.updateUser = updateUser;
		this.companies = companies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	public String getCrateUser() {
		return this.crateUser;
	}

	public void setCrateUser(String crateUser) {
		this.crateUser = crateUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
