package gr.scriptum.domain;

// Generated Jan 29, 2011 10:16:29 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private Integer id;
	private CompanyType companyType;
	private String name;
	private String description;
	private String address;
	private Boolean isGoverment;
	private String createUser;
	private Integer updateUser;
	private Date createDt;
	private Date updateTs;
	private String street;
	private String streetNo;
	private String city;
	private String prefecture;
	private String postcode;
	private String vatNo;
	private String irs;
	private String telephone;
	private String mobile;
	private String fax;
	private String email;
	private String web;
	private String webService;
	private Set<Contact> contacts = new HashSet<Contact>(0);

	public Company() {
	}

	public Company(CompanyType companyType) {
		this.companyType = companyType;
	}

	public Company(CompanyType companyType, String name, String description,
			String address, Boolean isGoverment, String createUser,
			Integer updateUser, Date createDt, Date updateTs, String street,
			String streetNo, String city, String prefecture, String postcode,
			String vatNo, String irs, String telephone, String mobile,
			String fax, String email, String web, String webService, Set<Contact> contacts) {
		this.companyType = companyType;
		this.name = name;
		this.description = description;
		this.address = address;
		this.isGoverment = isGoverment;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
		this.street = street;
		this.streetNo = streetNo;
		this.city = city;
		this.prefecture = prefecture;
		this.postcode = postcode;
		this.vatNo = vatNo;
		this.irs = irs;
		this.telephone = telephone;
		this.mobile = mobile;
		this.fax = fax;
		this.email = email;
		this.web = web;
		this.contacts = contacts;
		this.webService = webService;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CompanyType getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(CompanyType companyType) {
		this.companyType = companyType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Boolean getIsGoverment() {
		return this.isGoverment;
	}

	public void setIsGoverment(Boolean isGoverment) {
		this.isGoverment = isGoverment;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Integer getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getStreetNo() {
		return this.streetNo;
	}

	public void setStreetNo(String streetNo) {
		this.streetNo = streetNo;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPrefecture() {
		return this.prefecture;
	}

	public void setPrefecture(String prefecture) {
		this.prefecture = prefecture;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getVatNo() {
		return this.vatNo;
	}

	public void setVatNo(String vatNo) {
		this.vatNo = vatNo;
	}

	public String getIrs() {
		return this.irs;
	}

	public void setIrs(String irs) {
		this.irs = irs;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

	public String getWebService() {
		return webService;
	}

	public void setWebService(String webService) {
		this.webService = webService;
	}

}
