package gr.scriptum.domain;

// Generated May 25, 2011 9:59:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DiavgeiaDecisionType generated by hbm2java
 */
public class DiavgeiaDecisionType implements java.io.Serializable {

	private Integer id;
	private String uid;
	private String description;
	private String supported;
	private Date createDt;

	public DiavgeiaDecisionType() {
	}

	public DiavgeiaDecisionType(String uid, String description,
			String supported, Date createDt) {
		this.uid = uid;
		this.description = description;
		this.supported = supported;
		this.createDt = createDt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSupported() {
		return this.supported;
	}

	public void setSupported(String supported) {
		this.supported = supported;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

}
