package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DistributionMethod generated by hbm2java
 */
public class DistributionMethod implements java.io.Serializable {

	private Integer id;
	private String description;
	private String createUser;
	private String updateUser;
	private Date createDt;
	private Date updateTs;
	private Set<OutgoingProtocol> outgoingProtocols = new HashSet<OutgoingProtocol>(
			0);
	private Set<IncomingProtocol> incomingProtocols = new HashSet<IncomingProtocol>(
			0);

	public DistributionMethod() {
	}

	public DistributionMethod(String description, String createUser,
			String updateUser, Date createDt, Date updateTs,
			Set<OutgoingProtocol> outgoingProtocols,
			Set<IncomingProtocol> incomingProtocols) {
		this.description = description;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
		this.outgoingProtocols = outgoingProtocols;
		this.incomingProtocols = incomingProtocols;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	public Set<OutgoingProtocol> getOutgoingProtocols() {
		return this.outgoingProtocols;
	}

	public void setOutgoingProtocols(Set<OutgoingProtocol> outgoingProtocols) {
		this.outgoingProtocols = outgoingProtocols;
	}

	public Set<IncomingProtocol> getIncomingProtocols() {
		return this.incomingProtocols;
	}

	public void setIncomingProtocols(Set<IncomingProtocol> incomingProtocols) {
		this.incomingProtocols = incomingProtocols;
	}

}
