package gr.scriptum.domain;

// Generated Jan 29, 2011 1:29:09 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentType generated by hbm2java
 */
public class DocumentType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Integer isPeriodic;
	private Integer days;
	private String createUser;
	private String updateUser;
	private Date createDt;
	private Date updateTs;
	private Set<ProtocolDocument> protocolDocuments = new HashSet<ProtocolDocument>(
			0);

	public DocumentType() {
	}

	public DocumentType(String name, String description, Integer isPeriodic, Integer days,
			String createUser, String updateUser, Date createDt, Date updateTs,
			Set<ProtocolDocument> protocolDocuments) {
		this.name = name;
		this.description = description;
		this.isPeriodic = isPeriodic;
		this.days = days;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
		this.protocolDocuments = protocolDocuments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getIsPeriodic() {
		return this.isPeriodic;
	}

	public void setIsPeriodic(Integer isPeriodic) {
		this.isPeriodic = isPeriodic;
	}

	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	public Set<ProtocolDocument> getProtocolDocuments() {
		return this.protocolDocuments;
	}

	public void setProtocolDocuments(Set<ProtocolDocument> protocolDocuments) {
		this.protocolDocuments = protocolDocuments;
	}

}
