package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

/**
 * OutgoingRecipient generated by hbm2java
 */
public class OutgoingRecipient implements java.io.Serializable {

	public enum RecipientType {
		TO, CC, BCC
	};
	
	RecipientType recipientType = RecipientType.TO;
	
	/**
	 * No bug here since CC has index 1 and isCC takes value 1 to indicate this is a cc mail.
	 * @return the type of Recipient to, cc, bcc
	 */
	public RecipientType getRecipientType(){
	   return RecipientType.values()[isCc.intValue()];
	}
	
	//remember TO is 0, CC is 1
	public void setRecipientType(  RecipientType t ){
		setIsCc( new Integer( t.ordinal()));
	}
	
	
	
	private OutgoingRecipientId id;
	private Integer isCc;

	public OutgoingRecipient() {
	}

	public OutgoingRecipient(OutgoingRecipientId id) {
		this.id = id;
	}

	public OutgoingRecipient(OutgoingRecipientId id, Integer isCc) {
		this.id = id;
		this.isCc = isCc;
	}

	public OutgoingRecipientId getId() {
		return this.id;
	}

	public void setId(OutgoingRecipientId id) {
		this.id = id;
	}

	public Integer getIsCc() {
		return this.isCc;
	}

	public void setIsCc(Integer isCc) {
		this.isCc = isCc;
	}

}
