package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

/**
 * OutgoingRecipientId generated by hbm2java
 */
public class OutgoingRecipientId implements java.io.Serializable {

	private Contact contact;
	private OutgoingProtocol outgoingProtocol;

	public OutgoingRecipientId() {
	}

	public OutgoingRecipientId(Contact contact,
			OutgoingProtocol outgoingProtocol) {
		this.contact = contact;
		this.outgoingProtocol = outgoingProtocol;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public OutgoingProtocol getOutgoingProtocol() {
		return this.outgoingProtocol;
	}

	public void setOutgoingProtocol(OutgoingProtocol outgoingProtocol) {
		this.outgoingProtocol = outgoingProtocol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OutgoingRecipientId))
			return false;
		OutgoingRecipientId castOther = (OutgoingRecipientId) other;

		return ((this.getContact() == castOther.getContact()) || (this
				.getContact() != null
				&& castOther.getContact() != null && this.getContact().equals(
				castOther.getContact())))
				&& ((this.getOutgoingProtocol() == castOther
						.getOutgoingProtocol()) || (this.getOutgoingProtocol() != null
						&& castOther.getOutgoingProtocol() != null && this
						.getOutgoingProtocol().equals(
								castOther.getOutgoingProtocol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getContact() == null ? 0 : this.getContact().hashCode());
		result = 37
				* result
				+ (getOutgoingProtocol() == null ? 0 : this
						.getOutgoingProtocol().hashCode());
		return result;
	}

}
