package gr.scriptum.domain;

// Generated Jan 31, 2011 9:51:39 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Parameter generated by hbm2java
 */
public class Parameter implements java.io.Serializable {

	private Integer id;
	private String area;
	private String type;
	private String name;
	private String description;
	private String initialValue;
	private String value;
	private String createUser;
	private String updateUser;
	private Date createDt;
	private Date updateTs;

	public Parameter() {
	}

	public Parameter(String area, String type, String name, String description,
			String initialValue, String value, String createUser,
			String updateUser, Date createDt, Date updateTs) {
		this.area = area;
		this.type = type;
		this.name = name;
		this.description = description;
		this.initialValue = initialValue;
		this.value = value;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getInitialValue() {
		return this.initialValue;
	}

	public void setInitialValue(String initialValue) {
		this.initialValue = initialValue;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

}
