package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * ProjectUser generated by hbm2java
 */
public class ProjectUser implements java.io.Serializable {

	private ProjectUserId id;
	private String createUser;
	private String updateUser;
	private Date createDt;
	private Date updateTs;

	public ProjectUser() {
	}

	public ProjectUser(ProjectUserId id) {
		this.id = id;
	}

	public ProjectUser(ProjectUserId id, String createUser, String updateUser,
			Date createDt, Date updateTs) {
		this.id = id;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
	}

	public ProjectUserId getId() {
		return this.id;
	}

	public void setId(ProjectUserId id) {
		this.id = id;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

}
