package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

/**
 * ProjectUserId generated by hbm2java
 */
public class ProjectUserId implements java.io.Serializable {

	private Project project;
	private Users users;

	public ProjectUserId() {
	}

	public ProjectUserId(Project project, Users users) {
		this.project = project;
		this.users = users;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectUserId))
			return false;
		ProjectUserId castOther = (ProjectUserId) other;

		return ((this.getProject() == castOther.getProject()) || (this
				.getProject() != null
				&& castOther.getProject() != null && this.getProject().equals(
				castOther.getProject())))
				&& ((this.getUsers() == castOther.getUsers()) || (this
						.getUsers() != null
						&& castOther.getUsers() != null && this.getUsers()
						.equals(castOther.getUsers())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProject() == null ? 0 : this.getProject().hashCode());
		result = 37 * result
				+ (getUsers() == null ? 0 : this.getUsers().hashCode());
		return result;
	}

}
