package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Resource generated by hbm2java
 */
public class Resource implements java.io.Serializable {

	private Integer id;
	private String description;
	private String resource;
	private Set<Role> roles = new HashSet<Role>(0);

	public Resource() {
	}

	public Resource(String description, String resource, Set<Role> roles) {
		this.description = description;
		this.resource = resource;
		this.roles = roles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getResource() {
		return this.resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
