package gr.scriptum.domain;

/**
 * M.M. 3/2/2011
 * Class for interfacing task_document table in backend. Inherits from AbstractDocument. 
 */

import java.util.HashSet;
import java.util.Set;

/**
 * TaskDocument generated by hbm2java
 */
public class TaskDocument extends ScriptumDocument implements
		java.io.Serializable {

	private Set<ProjectTask> projectTasks = new HashSet<ProjectTask>(0);

	public TaskDocument() {
		super();
	}

	public TaskDocument(DocumentType documentType) {
		super(documentType);
	}

	public TaskDocument(Set<ProjectTask> projectTasks) {
		this.projectTasks = projectTasks;
	}

	public TaskDocument(Integer id, byte[] content, Long documentSize,
			String documentMime, String documentName, Integer documentNumber,
			String documentKeywords, DocumentType documentType,

			Set<ProjectTask> projectTasks) {
		super(id, content, documentSize, documentMime, documentName,
				documentNumber, documentKeywords, documentType);

		this.projectTasks = projectTasks;
	}

	public Set<ProjectTask> getProjectTasks() {
		return this.projectTasks;
	}

	public void setProjectTasks(Set<ProjectTask> projectTasks) {
		this.projectTasks = projectTasks;
	}

}
