package gr.scriptum.domain;

/**
 * M.M. 3/2/2011
 * Class for interfacing task_document table in backend. Inherits from AbstractDocument. 
 */



/**
 * TaskDocument generated by hbm2java
 */
public class TaskDocument extends ScriptumDocument implements
		java.io.Serializable {

	private ProjectTask projectTask;

	public TaskDocument() {
		super();
	}

	public TaskDocument(DocumentType documentType, ProjectTask projectTask) {
		super(documentType);
		this.projectTask = projectTask;
	}

	public TaskDocument(Integer id, byte[] content, Long documentSize,
			String documentMime, String documentName, Integer documentNumber,
			String documentKeywords, DocumentType documentType,ProjectTask projectTask) {
		super(id, content, documentSize, documentMime, documentName,
				documentNumber, documentKeywords, documentType);

		this.projectTask = projectTask;
	}

	public ProjectTask getProjectTask() {
		return projectTask;
	}

	public void setProjectTask(ProjectTask projectTask) {
		this.projectTask = projectTask;
	}


}
