package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * TaskMessage generated by hbm2java
 */
public class TaskMessage implements java.io.Serializable {

	private Integer id;
	private ProjectTask projectTask;
	private Users usersByUserReceiverId;
	private Users usersByUserSenderId;
	private String subject;
	private String message;
	private Date createdTs;

	public TaskMessage() {
	}

	public TaskMessage(ProjectTask projectTask, Users usersByUserReceiverId,
			Users usersByUserSenderId) {
		this.projectTask = projectTask;
		this.usersByUserReceiverId = usersByUserReceiverId;
		this.usersByUserSenderId = usersByUserSenderId;
	}

	public TaskMessage(ProjectTask projectTask, Users usersByUserReceiverId,
			Users usersByUserSenderId, String subject, String message,
			Date createdTs) {
		this.projectTask = projectTask;
		this.usersByUserReceiverId = usersByUserReceiverId;
		this.usersByUserSenderId = usersByUserSenderId;
		this.subject = subject;
		this.message = message;
		this.createdTs = createdTs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProjectTask getProjectTask() {
		return this.projectTask;
	}

	public void setProjectTask(ProjectTask projectTask) {
		this.projectTask = projectTask;
	}

	public Users getUsersByUserReceiverId() {
		return this.usersByUserReceiverId;
	}

	public void setUsersByUserReceiverId(Users usersByUserReceiverId) {
		this.usersByUserReceiverId = usersByUserReceiverId;
	}

	public Users getUsersByUserSenderId() {
		return this.usersByUserSenderId;
	}

	public void setUsersByUserSenderId(Users usersByUserSenderId) {
		this.usersByUserSenderId = usersByUserSenderId;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

}
