package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TaskState generated by hbm2java
 */
public class TaskState implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<ProjectTask> projectTasks = new HashSet<ProjectTask>(0);

	public TaskState() {
	}

	public TaskState(String name, String description,
			Set<ProjectTask> projectTasks) {
		this.name = name;
		this.description = description;
		this.projectTasks = projectTasks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ProjectTask> getProjectTasks() {
		return this.projectTasks;
	}

	public void setProjectTasks(Set<ProjectTask> projectTasks) {
		this.projectTasks = projectTasks;
	}

}
