package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TaskType generated by hbm2java
 */
public class TaskType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Integer isPeriodic;
	private Integer dayPeriod;
	private String createUser;
	private String updateUser;
	private Date createDt;
	private Date updateTs;
	private Set<ProjectTask> projectTasks = new HashSet<ProjectTask>(0);

	public TaskType() {
	}

	public TaskType(String name, String description, Integer isPeriodic,
			Integer dayPeriod, String createUser, String updateUser,
			Date createDt, Date updateTs, Set<ProjectTask> projectTasks) {
		this.name = name;
		this.description = description;
		this.isPeriodic = isPeriodic;
		this.dayPeriod = dayPeriod;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
		this.projectTasks = projectTasks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getIsPeriodic() {
		return this.isPeriodic;
	}

	public void setIsPeriodic(Integer isPeriodic) {
		this.isPeriodic = isPeriodic;
	}

	public Integer getDayPeriod() {
		return this.dayPeriod;
	}

	public void setDayPeriod(Integer dayPeriod) {
		this.dayPeriod = dayPeriod;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	public Set<ProjectTask> getProjectTasks() {
		return this.projectTasks;
	}

	public void setProjectTasks(Set<ProjectTask> projectTasks) {
		this.projectTasks = projectTasks;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TaskType other = (TaskType) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
