package gr.scriptum.domain;

// Generated Oct 5, 2011 7:41:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String name;
	private String surname;
	private Boolean isDisabled;
	private String createUser;
	private String updateUser;
	private Date createDt;
	private Date updateTs;
	private String address;
	private String email;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<TaskMessage> taskMessagesForUserReceiverId = new HashSet<TaskMessage>(
			0);
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<ProjectUser> projectUsers = new HashSet<ProjectUser>(0);
	private Set<ProjectTask> projectTasksForUserCreatorId = new HashSet<ProjectTask>(
			0);
	private Set<ProjectTask> projectTasksForUserDispatcherId = new HashSet<ProjectTask>(
			0);
	private Set<UserHierarchy> userHierarchies = new HashSet<UserHierarchy>(0);
	private Set<TaskMessage> taskMessagesForUserSenderId = new HashSet<TaskMessage>(
			0);

	public Users() {
	}

	public Users(String password) {
		this.password = password;
	}

	public Users(String username, String password, String name, String surname,
			Boolean isDisabled, String createUser, String updateUser,
			Date createDt, Date updateTs, String address, String email,
			Set<Project> projects,
			Set<TaskMessage> taskMessagesForUserReceiverId, Set<Role> roles,
			Set<ProjectUser> projectUsers,
			Set<ProjectTask> projectTasksForUserCreatorId,
			Set<ProjectTask> projectTasksForUserDispatcherId,
			Set<UserHierarchy> userHierarchies,
			Set<TaskMessage> taskMessagesForUserSenderId) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.isDisabled = isDisabled;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
		this.address = address;
		this.email = email;
		this.projects = projects;
		this.taskMessagesForUserReceiverId = taskMessagesForUserReceiverId;
		this.roles = roles;
		this.projectUsers = projectUsers;
		this.projectTasksForUserCreatorId = projectTasksForUserCreatorId;
		this.projectTasksForUserDispatcherId = projectTasksForUserDispatcherId;
		this.userHierarchies = userHierarchies;
		this.taskMessagesForUserSenderId = taskMessagesForUserSenderId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Boolean getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	public Set<TaskMessage> getTaskMessagesForUserReceiverId() {
		return this.taskMessagesForUserReceiverId;
	}

	public void setTaskMessagesForUserReceiverId(
			Set<TaskMessage> taskMessagesForUserReceiverId) {
		this.taskMessagesForUserReceiverId = taskMessagesForUserReceiverId;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public Set<ProjectUser> getProjectUsers() {
		return this.projectUsers;
	}

	public void setProjectUsers(Set<ProjectUser> projectUsers) {
		this.projectUsers = projectUsers;
	}

	public Set<ProjectTask> getProjectTasksForUserCreatorId() {
		return this.projectTasksForUserCreatorId;
	}

	public void setProjectTasksForUserCreatorId(
			Set<ProjectTask> projectTasksForUserCreatorId) {
		this.projectTasksForUserCreatorId = projectTasksForUserCreatorId;
	}

	public Set<ProjectTask> getProjectTasksForUserDispatcherId() {
		return this.projectTasksForUserDispatcherId;
	}

	public void setProjectTasksForUserDispatcherId(
			Set<ProjectTask> projectTasksForUserDispatcherId) {
		this.projectTasksForUserDispatcherId = projectTasksForUserDispatcherId;
	}

	public Set<UserHierarchy> getUserHierarchies() {
		return this.userHierarchies;
	}

	public void setUserHierarchies(Set<UserHierarchy> userHierarchies) {
		this.userHierarchies = userHierarchies;
	}

	public Set<TaskMessage> getTaskMessagesForUserSenderId() {
		return this.taskMessagesForUserSenderId;
	}

	public void setTaskMessagesForUserSenderId(
			Set<TaskMessage> taskMessagesForUserSenderId) {
		this.taskMessagesForUserSenderId = taskMessagesForUserSenderId;
	}

}
