package gr.scriptum.domain;

// Generated Jan 19, 2011 4:36:37 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private Users users;
	private String username;
	private String password;
	private String name;
	private String surname;
	private Boolean isDisabled;
	private String createUser;
	private String updateUser;
	private Date createDt;
	private Date updateTs;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<TaskMessage> taskMessagesForUserReceiverId = new HashSet<TaskMessage>(
			0);
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<ProjectUser> projectUsers = new HashSet<ProjectUser>(0);
	private Set<ProjectTask> projectTasksForUserCreatorId = new HashSet<ProjectTask>(
			0);
	private Set<ProjectTask> projectTasksForUserDispatcherId = new HashSet<ProjectTask>(
			0);
	private Set<TaskMessage> taskMessagesForUserSenderId = new HashSet<TaskMessage>(
			0);

	public Users() {
	}

	public Users(Users users) {
		this.users = users;
	}

	public Users(Users users, String username, String name, String surname,
			String password, Boolean isDisabled, String createUser,
			String updateUser, Date createDt, Date updateTs,
			Set<Project> projects,
			Set<TaskMessage> taskMessagesForUserReceiverId, Set<Role> roles,
			Set<Users> userses, Set<ProjectUser> projectUsers,
			Set<ProjectTask> projectTasksForUserCreatorId,
			Set<ProjectTask> projectTasksForUserDispatcherId,
			Set<TaskMessage> taskMessagesForUserSenderId) {
		this.users = users;
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.isDisabled = isDisabled;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.createDt = createDt;
		this.updateTs = updateTs;
		this.projects = projects;
		this.taskMessagesForUserReceiverId = taskMessagesForUserReceiverId;
		this.roles = roles;
		this.userses = userses;
		this.projectUsers = projectUsers;
		this.projectTasksForUserCreatorId = projectTasksForUserCreatorId;
		this.projectTasksForUserDispatcherId = projectTasksForUserDispatcherId;
		this.taskMessagesForUserSenderId = taskMessagesForUserSenderId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Boolean getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public Date getUpdateTs() {
		return this.updateTs;
	}

	public void setUpdateTs(Date updateTs) {
		this.updateTs = updateTs;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	public Set<TaskMessage> getTaskMessagesForUserReceiverId() {
		return this.taskMessagesForUserReceiverId;
	}

	public void setTaskMessagesForUserReceiverId(
			Set<TaskMessage> taskMessagesForUserReceiverId) {
		this.taskMessagesForUserReceiverId = taskMessagesForUserReceiverId;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	public Set<ProjectUser> getProjectUsers() {
		return this.projectUsers;
	}

	public void setProjectUsers(Set<ProjectUser> projectUsers) {
		this.projectUsers = projectUsers;
	}

	public Set<ProjectTask> getProjectTasksForUserCreatorId() {
		return this.projectTasksForUserCreatorId;
	}

	public void setProjectTasksForUserCreatorId(
			Set<ProjectTask> projectTasksForUserCreatorId) {
		this.projectTasksForUserCreatorId = projectTasksForUserCreatorId;
	}

	public Set<ProjectTask> getProjectTasksForUserDispatcherId() {
		return this.projectTasksForUserDispatcherId;
	}

	public void setProjectTasksForUserDispatcherId(
			Set<ProjectTask> projectTasksForUserDispatcherId) {
		this.projectTasksForUserDispatcherId = projectTasksForUserDispatcherId;
	}

	public Set<TaskMessage> getTaskMessagesForUserSenderId() {
		return this.taskMessagesForUserSenderId;
	}

	public void setTaskMessagesForUserSenderId(
			Set<TaskMessage> taskMessagesForUserSenderId) {
		this.taskMessagesForUserSenderId = taskMessagesForUserSenderId;
	}

}
