package gr.scriptum.domain;

// Generated Oct 5, 2011 7:41:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserHierarchy generated by hbm2java
 */
public class UserHierarchy implements java.io.Serializable {

	private Integer id;
	private UserHierarchy userHierarchy;
	private Department department;
	private Users users;
	private Set<UserHierarchy> userHierarchies = new HashSet<UserHierarchy>(0);

	public UserHierarchy() {
	}

	public UserHierarchy(Department department, Users users) {
		this.department = department;
		this.users = users;
	}

	public UserHierarchy(UserHierarchy userHierarchy, Department department,
			Users users, Set<UserHierarchy> userHierarchies) {
		this.userHierarchy = userHierarchy;
		this.department = department;
		this.users = users;
		this.userHierarchies = userHierarchies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserHierarchy getUserHierarchy() {
		return this.userHierarchy;
	}

	public void setUserHierarchy(UserHierarchy userHierarchy) {
		this.userHierarchy = userHierarchy;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Set<UserHierarchy> getUserHierarchies() {
		return this.userHierarchies;
	}

	public void setUserHierarchies(Set<UserHierarchy> userHierarchies) {
		this.userHierarchies = userHierarchies;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserHierarchy other = (UserHierarchy) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
