package gr.scriptum.eprotocol.util;

public enum Permission {

	WRITE_INCOMING, WRITE_OUTGOING, SEARCH_BOOK, ASSIGN_INTERNAL_RECIPIENTS, 
	DELETE_PROTOCOL, DISASSOCIATE_PROTOCOL, SEARCH_ALL_DEPARTMENTS, BATCH_ROUTE, 
	ADMINISTER,EDIT_PROTOCOL_DOCUMENTS,EDIT_PROTOCOL,
	ADD_COMPANY, EDIT_COMPANY, EXPORT_REPORTS_ALL_DEPARTMENTS,
	ADD_CONTACT,EDIT_CONTACT;
}
